Adding workflow consistency check
Signed-off-by: Janusz Wiśniowski <janusz@januszwisniowski.it>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,6 +50,11 @@ jobs:
           [[ '${{ steps.configuration.outputs.is_pr }}' ]] && echo "Running on a pull-request (${{ steps.configuration.outputs.is_fork_pr && 'from a fork' || 'internal' }})."  >> $GITHUB_STEP_SUMMARY
           [[ '${{ steps.configuration.outputs.is_pr }}' ]] && exit 0
           echo "Publish version is ${{ steps.get_publish_version.outputs.version }} (${{ steps.configuration.outputs.is_release && 'RELEASE' || 'SNAPSHOT' }} version)." >> $GITHUB_STEP_SUMMARY
+      - name: Validate configuration consistency
+        if: ${{ steps.configuration.outputs.is_fork_pr && !steps.configuration.outputs.is_pr || steps.configuration.outputs.is_release && !startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          echo 'Failed to configure workflow.'
+          exit 1
 
   validation:
     name: Validate Gradle wrapper
